#  +------------------------------------------------------------------------------------------------------------------------------+
#  |    _____   _       _____   __   __   _____      _   _   _   _   _   _____   _____   _____   _       _____   _____   _____    |
#  |   /  ___\ | |     |_   _| |  \_/  | |  ___|    | | | | | | | | | | |_   _| |_   _| |  ___| | |     |_   _| /  ___\ |_   _|   |
#  |   | |___  | |       | |   |       | | |___     | | | | | | | |_| |   | |     | |   | |___  | |       | |   | |___    | |     |
#  |   |___  | | |       | |   | |\_/| | |  ___|    | | | | | | |  _  |   | |     | |   |  ___| | |       | |   |___  |   | |     |
#  |    ___| | | |___   _| |_  | |   | | | |___     | |_| |_| | | | | |  _| |_    | |   | |___  | |___   _| |_   ___| |   | |     |
#  |   \_____/ |_____| |_____| |_|   |_| |_____|     \_______/  |_| |_| |_____|   |_|   |_____| |_____| |_____| \_____/   |_|     |
#  |                                                                                                                              |
#  |                                                                                                                              |
#  |   Разработчик: SoKnight                                                                                      Версия: 1.0.1   |
#  |                                                                                                                              |
#  +------------------------------------------------------------------------------------------------------------------------------+
#   
# Конфигурация базы данных
database:
  # Тип базы данных: [mysql, sqlite]
  type: sqlite
  # Конфигурация MySQL
  host: localhost
  port: 3306
  name: players
  user: admin
  password: slimewhitelist
  # Конфигурация SQLite
  file: players.db
#
# Выводить ли некоторые сообщения в консоль
info-to-console: true
#
# Максимальное оффлайн-время для авто-кика (в днях)
max-offline-time: 14
#
# Период очистки базы данных (в минутах)
purge-period: 60
#
# Форматирование даты
date-formating:
  # Настройка формата единиц времени
  units:
    years: '&b%y% г.'
    months: '&b%M% мес.'
    weeks: '&b%w% нед.'
    days: '&b%d% д.'
    hours: '&b%H% ч.'
    minutes: '&b%m% мин.'
  # Разделитель между единицами времени в строке
  separator: " "